### ISSUE TITLE
Format cannot be set in config file

### ISSUE THREAD

**Issue by guyilin-amazon** [awslabs/amazon-qldb-shell#132]
If we specify the format to be `table` in config file
```
[ui]
format = "table"
```
The format would still be `ion` after we started the Shell
```
qldb> \env
ShellConfig { ui: UiConfig { auto_commit: true, prompt: None, format: Ion, edit_mode: Emacs, display_welcome: true, display_ctrl_signals: true, display_query_metrics: true, terminator_required: false }, debug: DebugConfig { log: None }, default_ledger: None, ledgers: None }
```
Currently the `table` format could only be set through CLI opts, i.e. `qldb --format table`

**Comment by marcbowes** [comment]
@guyilin-amazon please confirm this is fixed for you by pulling the latest changes from the rust branch.
