### ISSUE TITLE
Vague error using shell without aws config

### ISSUE THREAD

**Issue by brack** [awslabs/amazon-qldb-shell#166]
This could be from the perspective of a first-time user who didn't fully set up their environment, or, could simply be someone who uses the shell a lot on a bunch of hosts, but is now on a remote host where their environment isn't fully configured.

As a user starting up QLDB shell without any AWS credentials configured, I would like to see an error that clearly indicates what the issue is or what is the next step to take. 

Current behavior: I get the following error, and I can see that it mentions 'credentials' which hints at it being an issue with AWS credentials. However, I wonder if we could catch this and throw a more clear error with next steps to the customer.

E.g., "Error: could not find AWS credentials. Please configure per https://docs.aws.amazon.com/qldb/latest/developerguide/accessing.html#setting-up-configure-credentials"

```
% qldb --ledger ihavenoawsconfig
thread '<unnamed>' panicked at 'A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/time/driver/handle.rs:55:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'credentials (or an error) should always come back: RecvError', src/credentials.rs:75:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by marcbowes** [comment]
That's a regression, thanks for finding! For ref, here's what 1.0 does..

```
❯ qldbshell --ledger nocreds

Traceback (most recent call last):
  File "/usr/local/bin/qldbshell", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/qldbshell/__main__.py", line 86, in main
    shell = QldbShell(args.profile, pooled_driver=pooled_driver)
  File "/usr/local/lib/python3.9/site-packages/qldbshell/qldb_shell.py", line 67, in __init__
    raise NoCredentialError("No credentials present") from None
qldbshell.errors.NoCredentialError: No credentials present
```

**Comment by marcbowes** [comment]
@brack please verify the fix then close :)

**Comment by brack** [comment]
@marcbowes the delay is a bit odd, i saw that it eventually does error out, but it shows the welcome message prior to the delay.

i don't want to overly complicate this, but i wonder if we could echo out 'loading configs and connecting to ledger...' instead of the welcome message, and only show the welcome message if there's a successful load. at the very least maybe we can avoid showing the welcome message. what do you think? 

overall i like the error message that comes back. super helpful.

**Comment by marcbowes** [comment]
> @marcbowes the delay is a bit odd, i saw that it eventually does error out, but it shows the welcome message prior to the delay. [edit: i see now in the PR the reason for why. i agree not ideal, but makes sense, and can be lived with IMO]

I don't think we'll have to live with this one for long. The sdk folks are working quickly on the support we need, then we can ditch the rusoto providers.

> i don't want to overly complicate this, but i wonder if we could echo out 'loading configs and connecting to ledger...' instead of the welcome message, and only show the welcome message if there's a successful load. at the very least maybe we can avoid showing the welcome message. what do you think?

It's tricky because *most of the time*, users will have correct credentials, and then there's more noise on the screen. To work around that, we can do fancy terminal stuff (like delete the text post connection), which reduces portability (e.g. cmd.exe on Windows).

I'm inclined to just wait this one out and revisit.

> overall i like the error message that comes back. super helpful.

👍

**Comment by marcbowes** [comment]
(And, of course, if you run the shell from an EC2 instance (including Cloud Shell), it'll find your credentials!)

**Comment by brack** [comment]
sounds good, i think if there were a straightforward way to indicate 'loading...' or suppress the welcome message, i'd say it's worth pursuing, but if not, i agree that most of the time people will have correct credentials. and, if the AWS SDK folks are providing a path to a fix for the 30-second delay, it sounds like minimal work would be needed on our side to improve the first-time customer experience.

i'll keep an eye on the issue you opened with aws-rust-sdk. it might make sense to have a backlog on our side as well, which i can create. closing this one out

**Comment by marcbowes** [comment]
https://github.com/awslabs/smithy-rs/pull/709 adds support for IMDS creds in the new SDK, which I think is the last piece we needed to migrate over. It also has 1s timeout (not 30s), which will fix this issue.
