### ISSUE TITLE
2.0 - unable to complete transaction after getting an error back from previous transaction

### ISSUE THREAD

**Issue by brack** [awslabs/amazon-qldb-shell#174]
If I get an error back, such as typing the wrong table name, my next transaction fails to complete. It seems to go into a multi-line mode and not even CTRL-D exits, when usually it would exit my multi-line query.

```
% qldb --ledger vehicle-registration
qldb> begin
qldb *> select * from Vehicles
communication failure: BadRequestException: Semantic Error: at line 1, column 15: No such variable named 'Vehicles'; No such variable named 'Vehicles'
qldb> begin
qldb *> select * from Vehicle

^D
^D
^C
%
```

**Comment by brack** [comment]
Another example _("oops I hit enter too early" or "oops i hit option-enter instead of esc-enter")_

```
qldb *> SELECT * FROM Vehicle AS v
WHERE v.VIN = '1N4AL11D75C109151'
AND

communication failure: BadRequestException: Parser Error: at line 3, column 1: expected expression, OPERATOR : and; Missing right-hand side expression of infix operator
qldb> begin
qldb *> SELECT * FROM Vehicle AS v
WHERE v.VIN = '1N4AL11D75C109151'



^D
^D
^C
```

I am then stuck and forced to exit the shell entirely

**Comment by marcbowes** [comment]
Are you running the latest version? I think this was fixed in 32062412803b9a6834399889f0648054d8ccc37b.

**Comment by brack** [comment]
using alpha13 -- will build from source and re-test

**Comment by brack** [comment]
tested with the latest version of the shell, and it's working as expected. closing
