### ISSUE TITLE
2.0 - default config not being created

### ISSUE THREAD

**Issue by brack** [awslabs/amazon-qldb-shell#178]
On both alpha13 and after building from source and installing the binary locally, the default config does not seem to be created. The ~/.config/qldbshell/ directory exists but no config exists. This is resulting in certain default behavior being off, e.g., auto_commit: false. I'm using macOS.

Here's `\env` when there's no config:
```
ShellConfig { ui: UiConfig { auto_commit: false, prompt: None, format: Ion, edit_mode: Emacs, display_welcome: false, display_ctrl_signals: false, display_query_metrics: false, terminator_required: false }, debug: DebugConfig { log: None }, default_ledger: None, ledgers: None }
```

I'm also wondering if I should open a separate issue for things defaulting to false (e.g., auto_commit, display_welcome, etc). Should the user be required to have a config file to have our expected default behaviors set automatically?

**Comment by marcbowes** [comment]
This is expected behavior, and consistent with other unix programs. Feel free to open issues to track defaults that you think are wrong.

**Comment by brack** [comment]
This makes sense. For some reason, I thought I saw that the config would be created, but I misread the readme. Will open a separate issue re: defaults
