### ISSUE TITLE
Feature Request: Split PartiQL statement across multiple lines

### ISSUE THREAD

**Issue by mlewis7127** [awslabs/amazon-qldb-shell#26]
It would be great if there was a way of entering PartiQL statement on multiple lines like you can in the console. You can paste in:

```
qldbshell > INSERT INTO Person
            << {
                'FirstName' : 'Raul',
                'LastName' : 'Lewis',
                'DOB' : `1963-08-19T`,
                'GovId' : 'LEWISR261LL',
                'GovIdType' : 'Driver License',
                'Address' : '1719 University Street, Seattle, WA, 98109'
            } >> 
```

which works fine, but I can't find a way of typing directly a long PartiQL statement into the shell without having to keep it all on one line

**Comment by marcbowes** [comment]
@mlewis7127 

If you're willing to live on the bleeding edge, try checkout the 'rust' branch. It supports *pasting* multiline inputs (but not typing them in - yet). You need to build it from source, and the installation instructions are not particularly detailed!

**Comment by marcbowes** [comment]
@mlewis7127 see https://github.com/awslabs/amazon-qldb-driver-rust/pull/27 which improves multiline support for bags. If you type `INSERT INTO Person <<` and then press return, you'll be able to continue on the next line (until you complete the bag with `>>` and press return).

**Comment by mlewis7127** [comment]
This is great. Worked for me and is exactly what I was looking for

**Comment by marcbowes** [comment]
@mlewis7127 also pushed a feature yesterday: https://github.com/awslabs/amazon-qldb-shell/commit/982af0037814358e2c3dc9651640b232a1157d4e. You can now pass a flag in that requires a delimiter (currently hardcoded to semicolon) rather than implicitly sending stuff when you press return.

> the following is now possible:

    qldbshell ... --terminator-required
    qldb> begin;
    qldb> insert into
    people {'name':'Bobby'}
    ;

**Comment by marcbowes** [comment]
Latest commits allow for `ALT+ENTER` (`SHIFT+ENTER` on Windows) to force a newline regardless.
