### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by terlar** [awslabs/amazon-qldb-shell#329]
Is there a plan for a new release of this soon?

There is a quite annoying bug (for some people) in the currently released version due to the version of the dependency `aws-config`. It does not have support for all profile names.

The pinned version `v0.0.20-alpha` does not have full support for profiles, but has been fixed in the current version `0.3.0` on the main branch.

See the problematic lines:
https://github.com/awslabs/aws-sdk-rust/blob/v0.0.20-alpha/sdk/aws-config/src/profile/parser/normalize.rs#L128-L137

**Comment by allimn** [comment]
Thanks for raising this issue. We will schedule a release upon your request asap.

**Comment by marcbowes** [comment]
Looks like main already has the right version

https://github.com/awslabs/amazon-qldb-shell/blob/2ba24f3332ed3c2579d4f1d31e5dbf2cf473c94c/Cargo.lock#L150-L151

and so the release should need no code changes.

**Comment by terlar** [comment]
I can verify that this new release do fix the issue I had with the profile, thank you very much!
