### ISSUE TITLE
Implement "\show ledgers"

### ISSUE THREAD

**Issue by justing-bq** [awslabs/amazon-qldb-shell#42]
Implement the command "show ledgers" so we can see the available ledgers.

Similar to "show tables"

**Comment by marcbowes** [comment]
I'm not a fan of this, as it requires a dependency on the control plane client. I think customers can use

```
aws qldb list-ledgers
```

and, doing so inside the shell repl has little additional value. If we really want, we could offer a 'subshell' escape hatch:

```
qldb> \! aws qldb list-ledgers
```

(feel free to bikeshed on syntax). psql has something similar: https://www.postgresql.org/docs/10/app-psql.html

```
\! [ command ]

    With no argument, escapes to a sub-shell; psql resumes when the sub-shell exits. With an argument, executes the shell command command.

    Unlike most other meta-commands, the entire remainder of the line is always taken to be the argument(s) of \!, and neither variable interpolation nor backquote expansion are performed in the arguments. The rest of the line is simply passed literally to the shell.
```

**Comment by marcbowes** [comment]
@alpian if you agree with this, we should close this issue and update the design doc.

**Comment by alpian** [comment]
Agree, let's explore the sub-shell idea.
